test:
  # Integration testing does not use 'port' settings so we must use 80...
  asset_port: 80
  tags:     ON
  captcha:  ON
  sphinx:   OFF
  worker:   OFF

development:
  asset_port: 7999
  mongrel:   ON
  passenger: OFF
  pdf:
    switch: ON
    engine: prince

  math:
    switch: ON
    live:   ON

  tags:     ON
  captcha:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.development.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'

production:
  # Port used only to provide assets during custom rendering (pdf).
  # We need this to avoid deadlocks.
  asset_port: 7999
  mongrel:   ON
  passenger: OFF
  pdf:
    switch: ON
    engine: prince
  math:
    switch: ON
    live:   ON
  tags:     ON
  captcha:  ON
  sphinx:
    switch: OFF
    activate_if:
      gem: 'thinking_sphinx'
      adapter: 'mysql,postgresql'
    run_if:
      file: 'log/searchd.production.pid'
  worker:
    switch:  OFF
    activate_if:
      gem: 'delayed_job'
