hpricot:
gettext:        '>= 1.93.0'
querybuilder:   '= 0.5.8'
rubyless:       '>= 0.3.5'
ruby-recaptcha: '= 1.0.0'
syntax:         '= 1.0.0'
tzinfo:         '>= 0.3.12'
uuidtools:      '= 2.0.0'
rails:          '= 2.3.4'
json:           '>= 1.1.9'
authlogic:      '= 2.1.3'
fast_gettext:   '~> 0.4.16'
will_paginate:  '~> 2.3.12'
differ:         '>= 0.1.1'
shoulda:        '>= 2.10.2'

querybuilder:   '>= 0.6.0'
yamltest:       '>= 0.5.3'
rubyless:       '>= 0.5.0'
property:       '>= 0.9.2'
versions:       '>= 0.2.1'
zafu:           '>= 0.6.0'

jeweler:

RedCloth:
  lib:          'redcloth'
  version:      '= 3.0.4'

rmagick:
  optional:     yes
  lib:          'RMagick'
  version:      '>= 2.10.0'

thinking-sphinx:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx'
  version:      '>= 1.3.14'

ts-delayed-delta:
  optional:     yes
  brick:        sphinx
  lib:          'thinking_sphinx/deltas/delayed_delta'
  version:      '>= 1.0.2'

delayed_job:
  optional:     yes
  version:      '>= 1.8.4'
